### ISSUE TITLE
Further tweak cleanstr flagging threshold to deal with feedback received

### ISSUE THREAD

**Issue by dcadenas** [planetary-social/cleanstr#38]
See [this nostr note](https://njump.me/note1348ew224kxfgl9lmmz4wkkvd9kuh8cfa6lf95pm6s6q2rdjl6gmqgw8aed) from this [slack convo](https://planetary-app.slack.com/archives/C060SF0SUQY/p1705607964634669)

**Comment by dcadenas** [comment]
One example of this is https://njump.me/nevent1qqsy5wrjrmxd2ax5am2r88ac9yatj2w8txypqdldjamj5j3lg73wgtszyzka2xgtu3nnw6z5dsvt2ew68f5eys0sup48tckmcql3se3ardajwn2z9js is a report that flags the referred [Chinese note](https://njump.me/nevent1qqsfnfsnkzzfgfhnzhl5yhpqkqqawync9yywrke4j4xdtnng4c6l3uspz3mhxue69uhhyetvv9ujumn0wd68ytnzvuq3vamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet5qgsrnnheq9usuua488uu3u345l6du4x80ljy0694vx32m6x2g94rq9qlmtepu) but when the content is translated to english or spanish, it's not flagged

**Comment by setch-l** [comment]
Daniel has made some updates since this ticket was created. Closing for now
