### ISSUE TITLE
[Account Moderation] Update encrypted message to support nprofiles

### ISSUE THREAD

**Issue by setch-l** [planetary-social/cleanstr#44]
- Update the encrypted messages in the Reportinator to support encyrption of nprofiles 
- Update encrypted messages in iOS to support encryption of nprofiles

**Comment by mplorentz** [comment]
I'm not sure `nprofile` is the right term here, unless I am missing something. Nprofile is a specific way to represent a nostr account, that also embeds relay info for the user. It's mean for humans to copy/paste into apps, and it looks like `nprofile1x8fuk...`. When Nos sends account reports to Reportinator it should reference the account by putting their hexadecimal publicy key in an `e` tag.

**Comment by dcadenas** [comment]
I agree, but it would be a good idea to render nprofile links in the slack channel so njump knows were to fetch user info (probably either relay.nos.social or purplepag.es?) https://njump.me/nprofile1qqsgnmujh847dhq7f63e3aj80u38a92zjcnmpgeaezdkgrsn0vjkheg0w3g0v

**Comment by dcadenas** [comment]
>When Nos sends account reports to Reportinator it should reference the account by putting their hexadecimal publicy key in an `e` tag.

I think you meant in the `p` tag?
