### ISSUE TITLE
[Tagger bot] BE Updates

### ISSUE THREAD

**Issue by setch-l** [planetary-social/cleanstr#48]
We want to switch the account of the Reportinator to Tagger. 
npub - npub12m2t8433p7kmw22t0uzp426xn30lezv3kxcmxvvcrwt2y3hk4ejsvre68j

If you need the nsec, ask Linda

These are the places in the BE this switch needs to happen: 

- [x] Connect to cleanstr code 
- [x] Connect to reportinator code 
- [ ] Update links in https://relay.nos.social

**Comment by joshuatbrown** [comment]
We'll need this done before we can do https://github.com/planetary-social/nos/issues/1120, but I already opened [a PR for it](https://github.com/planetary-social/nos/pull/1159). We'll just have to wait to merge that PR until this is done.

**Comment by dcadenas** [comment]
I'll update the new private key variable in cleanstr once we do the deploy and also merge the ansible-scripts PR once nos is approved by apple and we deploy
